name: creating CI-CD Pipeline
on: workflow_dispatch
jobs:
  runs-on: ubuntu:latest
  steps:
    - name: Build a project 
      run: echo " Sucessfully Builded project"
    - name: Deploy a project 
      run: echo "Sucessfully deployed application"
